### ISSUE TITLE
Can't see the correct icon

### ISSUE THREAD

**Issue by drazde** [artkorsun/DelphiStyleBookmarks#4]
I'm a newbie of sublime...
I add DelphiStyleBookmarks to sublime and install the package. It work fine but I can't see the icons of bookmark! 
What can I do?

**Comment by shivan** [comment]
Which version of SublimeText do you use?
I tried here at v3, manually installing.
To see the icons, you have to extract it to the correctly named folder.

Packages\Delphi Style Bookmarks

**Comment by drazde** [comment]
Hi, 
I have v3, I try to put the icons in various folder:
C:\Program Files\Sublime Text 3\Packages\Delphi Style Bookmarks
C:\Program Files\Sublime Text 3\Packages\Delphi Style Bookmarks\icons
C:\Program Files\Sublime Text 3\Packages\DelphiStyleBookmarks
C:\Program Files\Sublime Text 3\Packages\DelphiStyleBookmarks\icons

Every times I restarte SublimeText, and I try also executing it like  administrator....
And always I see a ugly icons 
![immagine](https://user-images.githubusercontent.com/2643448/38923938-f57ebfa8-42fb-11e8-8347-cb7528286743.png)

**Comment by shivan** [comment]
Wrong folder. 

Correct is `%AppData%\Sublime Text 3\Packages\Delphi Style Bookmarks`

**Comment by drazde** [comment]
Yea, 
Now I put the single file in subdirectory `icons` and it works!
`%AppData%\Sublime Text 3\Packages\Delphi Style Bookmarks\icons`

This is not very intuitive (for me) but now works
Thanks @shivan

**Comment by shivan** [comment]
I have put the complete Plugin to %AppData%\Sublime Text 3\Packages\Delphi Style Bookmarks
I don't have the plugin installed in C:\Program Files. Because C:\Program Files is a secure location where you can only put files as admin. Simply move the plugin directory to the described AppData-Directory and then it should work. At least this is how I am using it.

**Comment by drazde** [comment]
> I have put the complete Plugin to %AppData%\Sublime Text 3\Packages\Delphi Style Bookmarks

I don't have much confidence with Sublime (I'm learning..), when I go to Preferences | Browse Packages...
It open the corect directory `%appdata%\Sublime Text 3\Packages` but when I installed the plugin the directory `Delphi Style Bookmarks` there wasn't...
